postgres:
  database: postgres
  user: postgres
  password: postgres
  host: db
  port: 5432
  minsize: 1
  maxsize: 5
postgres_test:
  database: test
  user: postgres
  password: postgres
  host: db
  port: 5432
  minsize: 1
  maxsize: 5

host: 127.0.0.1
port: 8080
redis:
  REDIS_HOST : localhost
  REDIS_PORT : 6379